# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/homework/computer_organization/lab3/icf.xdc

# IP: ip/dist_mem_im/dist_mem_im.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_im || ORIG_REF_NAME==dist_mem_im} -quiet] -quiet
