# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/exp/resource/exp2_3/exp2_3/exp2_3.srcs/sources_1/ip/dist_mem_im/dist_mem_im.xci
# IP: The module: 'dist_mem_im' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/exp/resource/exp2_3/exp2_3/exp2_3.srcs/sources_1/ip/dist_mem_im/dist_mem_im_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_im'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/exp/resource/exp2_3/exp2_3/exp2_3.srcs/sources_1/ip/dist_mem_im/dist_mem_im.xci
# IP: The module: 'dist_mem_im' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/exp/resource/exp2_3/exp2_3/exp2_3.srcs/sources_1/ip/dist_mem_im/dist_mem_im_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_im'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
